version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - "27017:27017"
    networks: 
      - mongo-compose-network
  api:
    image: api
    environment:
      - MONGODB_URI=mongodb://mongo:27017/
    ports:
      - '3333:3333'
    networks: 
      - mongo-compose-network
    depends_on:
      - mongodb
volumes:
  mongodb_data_container:
networks:
  mongo-compose-network:
    driver: bridge