name: CI CD

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - name: Start MongoDB
        run: docker-compose up --detach mongodb
      - run: yarn install --immutable --immutable-cache --check-cache
      - run: yarn nx run-many --target=test --projects=api,frontend --parallel
      - run: yarn nx run-many --target=build --projects=api,frontend --parallel
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.APP_GCP_SA_KEY }}'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install
      - name: Build
        run: yarn nx build
      - name: Push Image and Publish app to Google Cloud Run
        working-directory: ./packages/app
        run: |
          docker build -f /packages/api/europe-west1-docker.pkg.dev/diggr-staging/api:latest .
          docker push europe-west1-docker.pkg.dev/diggr-staging/diggr/api:latest
          gcloud run deploy app --image europe-west1-docker.pkg.dev/diggr-staging/diggr/api:latest --port 5000 --region europe-west1


